version: "3"

services:
  dpattern_1:
    container_name: dpattern_1
    image: dpattern
    ports:
      - 8000:8080
    volumes:
      - ./settings.json:/app/settings.json
  dpattern_2:
    container_name: dpattern_2
    image: dpattern
    ports:
      - 8000:8080
    volumes:
      - ./settings.json:/app/settings.json

networks:
  default:
