swagger: '2.0'
info:
  description: Набор сервисов для учета на предприятии /ООО Ромашка/
  version: "1.0.0"
  title: RestApi

produces:
  - application/json
  - application/xml
  - application/text
  - text/html

basePath: "/api"

paths:
  /reports/formats:
    get:
      summary: Получить список форматов для отчетов
      operationId: main.formats
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка 
  /reports/{category}/{format_type}:
    get:
      summary: Получить отчет по указанной категории и формату
      operationId: main.get_report
      parameters:
        - name: category
          in: path
          required: true
          type: string
          description: Категория данных для отчета (range, group, nomenclature, recipes)
        - name: format_type
          in: path
          required: true
          type: string
          description: Формат отчета (CSV, JSON, XML, RTF, MARKDOWN)
      responses:
        200:
          description: Успешная генерация отчета
          schema:
            type: string
        400:
          description: Неверные параметры
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка        
  /filter/{domain_type}:
    post:
      summary: Фильтрация данных по указанной модели
      operationId: main.filter_data
      consumes:
        - application/json
      produces:
        - text/html
      parameters:
        - name: domain_type
          in: path
          required: true
          type: string
          description: Тип модели для фильтрации (range, group, nomenclature, recipes)
        - in: body
          name: filter_dto
          description: DTO модель для фильтрации данных
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              unique_code:
                type: string
              type:
                type: integer
      responses:
        200:
          description: Успешная фильтрация данных
          schema:
            type: array
            items:
              type: object
        400:
          description: Неверные параметры фильтрации или тип данных
        404:
          description: Данные не найдены
        500:
          description: Ошибка на сервере
  /get/transactions:
    post:
      summary: Фильтрация складских транзакций по складу и номенклатуре
      tags:
        - Warehouse
      operationId: main.get_transactions
      consumes:
        - application/json
      produces:
        - text/html
      parameters:
        - in: body
          name: filter_data
          description: DTO модель для фильтрации складских транзакций
          required: true
          schema:
            type: object
            properties:
              warehouse:
                type: object
                properties:
                  name:
                    type: string
                  unique_code:
                    type: string
                  type:
                    type: integer
              nomenclature:
                type: object
                properties:
                  name:
                    type: string
                  unique_code:
                    type: string
                  type:
                    type: integer
      responses:
        200:
          description: Успешная фильтрация транзакций
          schema:
            type: array
            items:
              type: object
        400:
          description: Неверные параметры фильтрации
        404:
          description: Транзакции не найдены
        500:
          description: Ошибка на сервере
  /filter/turnover:
    post:
      tags:
        - Warehouse
      operationId: main.get_turnover
      consumes:
        - application/json
      produces:
        - application/json
      summary: Получение складских оборотов
      description: Позволяет получить складские обороты с фильтрацией по складу, номенклатуре и периоду.
      parameters:
        - in: body
          name: body
          description: Фильтры для складских оборотов
          required: true
          schema:
            type: object
            properties:
              warehouse:
                type: object
                description: Фильтры для склада
                properties:
                  name:
                    type: string
                    description: Имя склада
                  unique_code:
                    type: string
                    description: Код склада
                  type:
                    type: integer
                    description: Тип фильтрации
                    enum: [1, 2]  # 0 - EQUALS, 1 - LIKE
              nomenclature:
                type: object
                description: Фильтры для номенклатуры
                properties:
                  name:
                    type: string
                    description: Имя номенклатуры
                  unique_code:
                    type: string
                    description: Код номенклатуры
                  type:
                    type: integer
                    description: Тип фильтрации
                    enum: [1, 2]  # 1 - EQUALS, 2 - LIKE
              start_period:
                type: string
                format: date
                description: Начало периода (YYYY-MM-DD)
              end_period:
                type: string
                format: date
                description: Конец периода (YYYY-MM-DD)
      responses:
        200:
          description: Успешный ответ с данными оборотов
          schema:
            type: array
            items:
              type: object
              properties:
                warehouse:
                  type: string
                  description: Код склада
                nomenclature:
                  type: string
                  description: Код номенклатуры
                turnover:
                  type: number
                  description: Количество оборота
        404:
          description: Транзакции или обороты не найдены
        500:
          description: Ошибка на сервере
  /settings/set_block_period:
    post:
      tags:
        - Settings
      summary: Изменение даты блокировки
      description: Устанавливает новую дату блокировки в настройках.
      operationId: main.set_block_period
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: JSON с датой блокировки в формате YYYY-MM-DD.
          required: true
          schema:
            type: object
            properties:
              block_period:
                type: string
                format: date
                example: "2024-01-01"
      responses:
        200:
          description: Дата блокировки обновлена успешно.
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Дата блокировки обновлена успешно."
        400:
          description: Неправильный формат даты или ошибка запроса.
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Неправильный формат даты или ошибка запроса."
              details:
                type: string

  /settings/get_block_period:
    get:
      tags:
        - Settings
      summary: Получение текущей даты блокировки
      description: Возвращает текущую дату блокировки.
      operationId: main.get_block_period
      produces:
        - application/json
      responses:
        200:
          description: Текущая дата блокировки.
          schema:
            type: object
            properties:
              block_period:
                type: string
                format: date
                example: "2024-01-01"

  /api/nomenclature:
    get:
      summary: Получить номенклатуру
      tags:
        - Nomenclature
      produces:
        - text/html
      operationId: main.get_nomenclature
      description: Возвращает информацию о номенклатуре по уникальному коду.
      parameters:
        - name: unique_code
          in: query
          description: Уникальный код номенклатуры
          required: true
          type: string
      responses:
        200:
          description: Информация о номенклатуре
        400:
          description: Неверные параметры запроса
        404:
          description: Номенклатура не найдена

    put:
      summary: Добавить номенклатуру
      tags:
        - Nomenclature
      produces:
        - text/html
      operationId: main.add_nomenclature
      description: Создает новую номенклатуру.
      parameters:
        - in: body
          name: body
          description: Данные новой номенклатуры
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              full_name:
                type: string
              group_id:
                type: string
              range_id:
                type: string
      responses:
        201:
          description: Номенклатура успешно создана
        400:
          description: Неверные параметры запроса

    patch:
      summary: Обновить номенклатуру
      tags:
        - Nomenclature
      produces:
        - text/html
      operationId: main.update_nomenclature
      description: Обновляет существующую номенклатуру.
      parameters:
        - in: body
          name: body
          description: Данные для обновления номенклатуры
          required: true
          schema:
            type: object
            properties:
              unique_code:
                type: string
              name:
                type: string
              full_name:
                type: string
              group_id:
                type: string
              range_id:
                type: string
      responses:
        200:
          description: Номенклатура успешно обновлена
        400:
          description: Неверные параметры запроса
        404:
          description: Номенклатура не найдена

    delete:
      summary: Удалить номенклатуру
      tags:
        - Nomenclature
      produces:
        - text/html
      operationId: main.delete_nomenclature
      description: Удаляет номенклатуру по уникальному коду.
      parameters:
        - in: body
          name: body
          description: Уникальный код номенклатуры
          required: true
          schema:
            type: object
            properties:
              unique_code:
                type: string
      responses:
        200:
          description: Номенклатура успешно удалена
        400:
          description: Ошибка при удалении номенклатуры
        404:
          description: Номенклатура не найдена
  /api/report/osv:
    get:
      summary: Получить отчет по оборотно-сальдовой ведомости (ОСВ)
      description: Получить отчет по оборотно-сальдовой ведомости за указанный период и склад.
      operationId: main.get_osv_report
      produces:
        - application/json
      parameters:
        - in: query
          name: start_date
          required: true
          type: string
          format: date
          description: Начальная дата отчетного периода в формате `YYYY-MM-DD`.
        - in: query
          name: end_date
          required: true
          type: string
          format: date
          description: Конечная дата отчетного периода в формате `YYYY-MM-DD`.
        - in: query
          name: warehouse
          required: true
          type: string
          description: Идентификатор склада, для которого составляется отчет.
      responses:
        200:
          description: Отчет по оборотно-сальдовой ведомости за указанный период и склад.
          schema:
            type: object
            properties:
              initial_balance:
                type: number
                description: Начальный остаток на начало периода.
              inflow:
                type: number
                description: Общий приход за указанный период.
              outflow:
                type: number
                description: Общий расход за указанный период.
              final_balance:
                type: number
                description: Итоговый остаток на конец периода.
            example:
              initial_balance: 1000.0
              inflow: 500.0
              outflow: 300.0
              final_balance: 1200.0
        400:
          description: Некорректный запрос из-за отсутствия обязательных параметров.
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Отсутствуют обязательные параметры: 'start_date', 'end_date' или 'warehouse'."
        500:
          description: Внутренняя ошибка сервера.
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Произошла ошибка при обработке запроса."
      tags:
        - Отчеты
  /api/repository/save:
    post:
      summary: Сохранить данные репозитория в файл
      description: Сохраняет все данные из репозитория в файл.
      operationId: main.save_repository
      tags:
        - Repository
      produces:
        - application/json
      responses:
        200:
          description: Данные успешно сохранены в файл
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Данные успешно сохранены в файл."
        500:
          description: Ошибка при сохранении данных
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Ошибка при сохранении данных в файл."

  /api/repository/restore:
    post:
      summary: Восстановить данные репозитория из файла
      description: Восстанавливает все данные из файла в репозиторий.
      operationId: main.restore_repository
      tags:
        - Repository
      produces:
        - application/json
      responses:
        200:
          description: Данные успешно восстановлены из файла
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Данные успешно восстановлены из файла."
        500:
          description: Ошибка при восстановлении данных
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Ошибка при восстановлении данных из файла."

